### ISSUE TITLE
Increase WebHook error notifications coverage

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-bc-registries-agent#122]
While running tests on the new WebHook notifications a few processing errors were logged to the database, but the WebHook notifications did not provide any indication of the issues.

Processing (event_by_corp_filing) error example;
- current transaction is aborted, commands ignored until end of transaction block

Posting (credential_log) error example;
- Could not locate credential type: registration.registries.ca/1.0.40 None

Received WebHook Notification:
- `Ran bc_reg_event_processor`

**Comment by WadeBarnes** [comment]
Posting (credential_log) error notifications addressed by #139 and #140.

**Comment by swcurran** [comment]
@ianco - is this still an issue?  Do we need this implemented before the live ICOB OrgBook deployment?

**Comment by ianco** [comment]
I'll review the notifications we currently support and see if we need to add anything new.
