### ISSUE TITLE
Sovrin Mainnet version bumping to Indy-Node 1.9.0 - Are we OK?

### ISSUE THREAD

**Issue by swcurran** [bcgov/von-bc-registries-agent#148]
On July 22, Sovrin Mainnet will be bumped to:

- indy-node 1.9.0
- indy-plenum 1.9.0
- sovrin 1.1.50

Any concerns about BC Reg, OrgBook BC and OrgBook Ontario still working when that happens?

Assigning to Ian, but flagging @WadeBarnes as a heads up.

**Comment by WadeBarnes** [comment]
@andrewwhitehead, Do you need to make any updates to von-image so we can upgrade von-network in order to test?
