### ISSUE TITLE
BC Reg Controller Writing the same CRED_DEF to the ledger on each start-up

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-bc-registries-agent#164]
Look at the Ledger Transactions on http://dev.bcovrin.vonx.io
Filter by did = CswJVDiuLUj5tGdKRQUYfs
- Note there are 95+ records that have been written to the ledger by the controller through the agent.  The controller is writing CRED_DEF records each time it starts up.

Filter the records by CRED_DEF = CswJVDiuLUj5tGdKRQUYfs:3:CL:827:default
- Note there are 30+ instances of the same CRED_DEF.

**Comment by swcurran** [comment]
@ianco - is this an issue?  I assume this is so that we can rerun from scratch in Dev without having to reset the ledger.  We don't do this in Prod because the wallet has the Cred Def in it.

Close? Change to backlog?  Fix/Change?

Thanks!

**Comment by swcurran** [comment]
Another ping @ianco about where this issue sits.  Is it needed to be resolved before we launch ICOB OrgBook?

**Comment by ianco** [comment]
I'll check to see what logic we can add to the controller.  I don't think this is a showstopper, but probably something e can fix.

**Comment by ianco** [comment]
see https://github.com/bcgov/von-bc-registries-agent/pull/189
