### ISSUE TITLE
Inconsistent status codes when posting credential to Controller

### ISSUE THREAD

**Issue by esune** [bcgov/von-bc-registries-agent#167]
This bug refers to the aries-cloudagent version of the bc-registries agent.

When posting credentials to the `/issue-credential` endpoint on the controller, the response codes are inconsistent with the actual result.

A result code of `200 OK` with a body content like the following is returned regardless of whether the credential was successfully issued or not:
```
[
  {
    "result": "e83b4b7f-479c-4c8f-91af-594d5f005b90::Error thread timeout",
    "success": false
  }
]
```

This happens both when:
- the credential is posted to the agent, but the agent throws an error and fails to issue the credential. In this cade, the status code should be in the `5xx` range, with an appropriate message.
- the credential id correctly posted to the agent. In this case a `200` status code is correct, but the message body should specify `success: true`

Similarly, when a request submitted to the controller doesn't meet the requirements, a generic `400` response without details is returned: some context on what went wrong would definitely be helpful.

**Comment by ianco** [comment]
The controller should always return a 200 response (unless there is an error in the controller itself).  The contents of the response should indicate if the credential was posted successfully or not.  (The contents should be an array, one element for each credential in the request.)

The timeout occurs if the controller does not know the status of the credential submission.  This can occur if there is an un-trapped error (in either agent, or in ICOB) or (as Wade has found) if there are multiple instances of the controller and the callback comes back to the wrong controller (i.e. not the one that sent the request).

We need to find out why the controller is not getting the response.  Note that it comes via an asynchronous callback.  

The request is sent to the agent here:  https://github.com/bcgov/von-bc-registries-agent/blob/aries-refactoring/bcreg-aca/src/issuer.py#L461 ...  and then the join() on the next line waits for the response.

A successful response will call this callback:  https://github.com/bcgov/von-bc-registries-agent/blob/aries-refactoring/bcreg-aca/src/issuer.py#L314

An error should call this callback:  https://github.com/bcgov/von-bc-registries-agent/blob/aries-refactoring/bcreg-aca/src/issuer.py#L352

If neither of those callbacks is called, you will get a timeout.

**Comment by swcurran** [comment]
@esune - based on Ian's response, sounds like things are working correctly.  Is that right?  If so, can we close this?
