### ISSUE TITLE
Update AVIA controller to use new credential exchange API(s)

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-bc-registries-agent#216]
The AVIA controller (`aries-refactoring` branch) is currently using the older deprecated `/credential_exchange/send` API to issue credentials; https://github.com/bcgov/von-bc-registries-agent/blob/aries-refactoring/bcreg-aca/src/issuer.py#L714

Update the code to use the replacement, `/issue-credential/send`, API.

Payloads of the two APIs is different.

**Comment by ianco** [comment]
Issue with the new API.

In the "old" credential exchange /credential_exchange/{id}/store we could specify a credential_id to store in the wallet:

{
  "credential_id": "string"
}

In the "new" credential exchange /issue-credential/records/{cred_ex_id}/store we can't

We need to either update the new api to include the option to specify a credential_id, or else re-tool the VCR back-end to change the order in which the credential is saved (i.e. wallet first then VCR search database vs the other way around)

**Comment by ianco** [comment]
Work in progress in in branch:  fix-216-credential-api

(in indy-catalyst and vn-bc-registries-agent repositories)

**Comment by ianco** [comment]
Updated aca-py credential exchange api (allow controller to specify credential_id to be saved in the wallet).  PR merged but can't merge PR's for indy-catalyst or von-bc-registries-agent until the aca-py update is included in an official release (likely the next release 0.4.3).

Draft PR's are added to indy-catalyst and von-bc-registries-agent in anticipation

@WadeBarnes

**Comment by swcurran** [comment]
@ianco - is this complete now?
