### ISSUE TITLE
Promote BN Credential to Test

### ISSUE THREAD

**Issue by ianco** [bcgov/von-bc-registries-agent#264]
Promote code through dev and test prior to promoting to production.
Steps in dev:
- promote code to dev
- run script to generate BN credentials for existing orgs:
    `./run-step.sh bcreg/bc_reg_bn_cred_pipeline.py`
OR:
    `./run-step.sh bcreg/find-un-bned-corps.py`
    `./run-step.sh bcreg/process-corps-generate-bn-creds.py`
- run script to post BN credentials:
    `./run-step.sh bcreg/bc_reg_pipeline_post_credentials.py`
- test creds in orgbook

Steps in test:
- shut down cron job in test
- promote code to test
- run script to generate BN credentials for existing orgs:
    `./run-step.sh bcreg/bc_reg_bn_cred_pipeline.py`
- run script to post BN credentials:
    `./run-step.sh bcreg/bc_reg_pipeline_post_credentials.py`
- test creds in orgbook
- restart cron job in test

**Comment by ianco** [comment]
Currently testing in `dev` ...

**Comment by WadeBarnes** [comment]
Ping me when it's ready to go to `test`.

**Comment by ianco** [comment]
@WadeBarnes will do just having some issues with some of the query performance
