### ISSUE TITLE
Upgrade VON BC Reg dev/test environments with latest components in von-bc-registries-agent repo

### ISSUE THREAD

**Issue by swcurran** [bcgov/von-bc-registries-agent#3]
Ian has completed the first cut of the BC Registries Event process - including a BCReg-X based on VON-X and a Data Pipeline based on Mara.  There is also a Postgres database for tracking credential processing/publishing.

Please use Slack including Stephen and Ian for questions.  Ian may or may not reply since he is on vacation.

**Comment by WadeBarnes** [comment]
The components of the von-bc-registries-agent repository have been updated to run on OpenShift.  Build configurations have been created and deployed to `devex-von-bc-registries-agent-tools` and deployment configurations created and deployed to `devex-von-bc-registries-agent-dev`.

The `devex-von-bc-registries-agent-dev` environment has been wired to the `devex-von-bc-tob-dev` (`bc-tob`) environment and has populated that environment with the registry data from the BC Registries UAT environment.

[go-crond](https://github.com/webdevops/go-crond) is being used to run the data-pipelines every 15 minutes.  The executions are registered with mara and the details of the runs can be reviewed in the mara interface.

**Comment by WadeBarnes** [comment]
Next steps:
1. Create and deploy Jenkins pipelines for auto-triggered build/deployment of the components.  To this point builds and deployed have been performed manually using `oc` on the cmd line.
1. Roll things out to the TEST environment.

**Comment by WadeBarnes** [comment]
Jenkins pipelines for auto-triggered build/deployment have been created and deployed.

We can roll things out to TEST once things stabilize a bit more.
