### ISSUE TITLE
Reprocess entity XS0078660  because of a manual change made to the database

### ISSUE THREAD

**Issue by swcurran** [bcgov/von-bc-registries-agent#329]
Per David Roberts of BC Registries:

> I have updated the former name for XS0078660.  Please update the former name in Orgbook to:
> 
> CANADIAN FOOD INNOVATION NETWORK RESEAU CANADIEN D'INNOVATION EN ALIMENTATION

In OrgBook BC, that means we need to trigger this organization to be reloaded into OrgBook BC.

Assigning to @amanji , but perhaps this needs to wait for @WadeBarnes to return?

**Comment by amanji** [comment]
It looks like the credentials have been processed. Can you please check that information is correct on OrgBook BC ?

**Comment by amanji** [comment]
I'd also note that it seems the French name is displaying oddly due to the presence of Unicode characters in the name

**Comment by swcurran** [comment]
Nice — thanks!
