### ISSUE TITLE
Survey exposed API and determine what needs to be locked down

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-bc-registries-agent#33]
Review the REST API for the `bcreg-x-agent` and determine what services are OK to be open and what needs to be locked down - e.g. the issuance of credentials (`/bcreg/issue-credential`).

Once defined - document the items to be locked down and add a ticket to make it so.

**Comment by swcurran** [comment]
I don't think there should be any exposed API endpoints except the async callbacks from VON-X TOB and hence, protected by DIDAuth.

@ianco - can you confirm that?

IMHO - All access to the stats should go via command line by an OC command, or portforwarding to localhost for web access.

**Comment by WadeBarnes** [comment]
What can be exposed by an agent is the issuer's web page, or in the case of the Permitify service, a form that can be filled out to get a new credential.

Right now the URL registered with TOB directs the user back to the BC Reg Agent

![image.png](https://images.zenhubusercontent.com/5adfb6864b5806bc2bd08363/d79be435-8f05-4cc0-8549-12f39ce237fd)
