### ISSUE TITLE
Missing records in OrgBook dev/test

### ISSUE THREAD

**Issue by esune** [bcgov/von-bc-registries-agent#331]
It was reported that the following records, previously visible in dev/test, arenot there anymore.
![image](https://github.com/bcgov/von-bc-registries-agent/assets/2395873/67dc4bab-d74a-4107-95a4-874f4ca939a9)

**Comment by amanji** [comment]
We need to reprocess orgs in test since BCovrin test was reset.

**Comment by swcurran** [comment]
Any update on the progress on this?  Particularly the ones for MOTI.

**Comment by esune** [comment]
I believe @amanji and @WadeBarnes were going to connect, however it looks like it is mostly a matter of time for credentials to be processed and re-issued - I don't believe it is possible to re-issue credentials selectively without implementing ad-hoc scripts, the queue is processed as it is received.

**Comment by WadeBarnes** [comment]
The credentials are being reprocessed.  There are just under 3,000,000 left to post, which is expected to take another 26 hours.  Unfortunately there is not a built in way to single out individual credentials.

**Comment by WadeBarnes** [comment]
The average credential post rate has dropped a bit overnight.  There are a little over 1 million credentials left to post, which is expected to take about 18 hours.

**Comment by WadeBarnes** [comment]
Here is a more detailed summary based on the average credential posting rate over the last hour:

```
Credentials are being posted at an average rate of:
  - 25 per second, or
  - 1489 per minute
  - Over the period of 1h:0m:0s

  - Estimating 11h:17m:15s to process the remaining 1,008,354 credentials

Credential Summary:

 total_credentials | unprocessed | processed | posted  |  held   | errors
-------------------+-------------+-----------+---------+---------+--------
           5239218 |     1008354 |   4230864 | 2641821 | 1589043 |      0
```

**Comment by swcurran** [comment]
Should we spend the time to switch Dev to Askar and rerun the load to see what the impact is?  And with the latest ACA-Py, so we pick up the latest CL-Signatures code.  Although…the biggest speed ups in that have been with revocation on, so less of an impact on this.

**Comment by WadeBarnes** [comment]
All of the corp records have been reloaded into the OrgBook `test` environment.

**Comment by swcurran** [comment]
Awesome! What was the overall rate of loading, and to end.

**Comment by WadeBarnes** [comment]
It fluctuated throughout the process due to the nature of how it processes in batches, but was mostly consistent at around 1800 credentials per minute when fully active.  Overall average was likely around 1400 credentials per minute.
