### ISSUE TITLE
Remove a registration update (that seems to have been) entered in error

### ISSUE THREAD

**Issue by swcurran** [bcgov/von-bc-registries-agent#333]
Per David Roberts:

> Hi Stephen and Wade
>  
> In Orgbook please remove the “System Dissolution Administrative” for BC1428771 and BC1271116.

No other details about why this is needed, or what triggered the change.

Do we know how to do this?

**Comment by WadeBarnes** [comment]
Assuming that event has been removed from the BC Registries side we can remove the entries and reprocess that records using the scripts from [bcgov/von-bc-registries-agent-configurations](https://github.com/bcgov/von-bc-registries-agent-configurations), and [bcgov/orgbook-configurations](https://github.com/bcgov/orgbook-configurations)

```
./manage -p bc -e prod deleteTopic BC1428771
./manage -e prod requeueOrganization 1428771
```

```
./manage -p bc -e prod deleteTopic BC1271116
./manage -e prod requeueOrganization 1271116
```

@rajpalc7 knows how to do this.

**Comment by rajpalc7** [comment]
This request is completed now.
