### ISSUE TITLE
Update parish registration dates

### ISSUE THREAD

**Issue by droberts27** [bcgov/von-bc-registries-agent#335]
Currently, the registration date in the BC Registries system for Parishes is set to a special value indicating not known. The dates are in paper files.  This issue is to track the need to reprocess the OrgBook BC registrations for the parishes once the paper data has been added to the database for the 49 registrations.  That work is currently in process and its completion will be noted here.

**Comment by WadeBarnes** [comment]
@droberts27, Can you provide some details on this request?  Thanks

**Comment by droberts27** [comment]
@WadeBarnes I have asked our staff member Robyn Murray to pull the 49 paper files so that I can get the registration date.

**Comment by swcurran** [comment]
Updated the task definition.

**Comment by WadeBarnes** [comment]
Crystal clear now.  Thanks @droberts27 and @swcurran

**Comment by swcurran** [comment]
Attached is a CSV from an OrgBook user with the list of parish names and registration dates that might be useful in double-checking the data.
[parishes.csv](https://github.com/bcgov/von-bc-registries-agent/files/13057052/parishes.csv)

If interested, I have the list as a markdown table that I can paste into this issue as well.

**Comment by ianco** [comment]
The parishes just need to be re-processed, to update OrgBook to the latest data in the source database.  So we just need the list of parishes, not the actual dates.

**Comment by swcurran** [comment]
The dates have been posted into the BC Registries database yet — that is in process. The CSV can be used to double-check the data (or perhaps as source, to be double-checked in the papers). Once that is done, we will reprocess the data in OrgBook BC.

**Comment by droberts27** [comment]
@swcurran Can you tell me anything more about the Orgbook user who provided the parishes.csv data?  Were there parishes more current than PAR 57?  We have up to PAR 77.

**Comment by swcurran** [comment]
Apologizes — I had used ChaptGPT to convert text to CSV and didn’t realize there was a “Continue generating” button.

The list I received was for up to PAR 76 (not 77) — attached is the full list.

[parishes.csv](https://github.com/bcgov/von-bc-registries-agent/files/13168071/parishes.csv)

**Comment by droberts27** [comment]
I have used the dates from the paper files to update the following parishes.  Please reprocess so that Orgbook will have the correct registration date.

CORP_NUM    EVENT_ID
-------------    -----------
PAR0000002 101987446
PAR0000003 101987452
PAR0000004 101987459
PAR0000005 101987469
PAR0000006 101987474
PAR0000007 101987479
PAR0000008 101987486
PAR0000009 101987496
PAR0000010 101987500
PAR0000011 101987510
PAR0000012 101987519
PAR0000013 101987521
PAR0000014 101987530
PAR0000015 101987536
PAR0000016 101987542
PAR0000017 101987545
PAR0000018 101987553
PAR0000019 101987556
PAR0000020 101987564
PAR0000021 101987568
PAR0000022 101987574
PAR0000023 101987582
PAR0000024 101987585
PAR0000025 101987595
PAR0000026 101987597
PAR0000027 101987607
PAR0000028 101987613
PAR0000029 101987617
PAR0000030 101987622
PAR0000031 101987627
PAR0000032 101987628
PAR0000033 101987637
PAR0000034 101987640
PAR0000035 101987643
PAR0000036 101987651
PAR0000037 101987655
PAR0000038 101987662
PAR0000039 101987665
PAR0000040 101987670
PAR0000041 101987676
PAR0000042 101987678
PAR0000043 101987684
PAR0000044 101987688
PAR0000045 101987697
PAR0000046 101987699
PAR0000047 101987707
PAR0000048 101987710
PAR0000049 101987714
PAR0000050 101987719

**Comment by swcurran** [comment]
@amanji — can you please take care of this?  I assume it is straight forward to do?

**Comment by droberts27** [comment]
If you re-process the events above will that update the registration dates?

**Comment by swcurran** [comment]
Actually assigning this to @amanji to do.  Doh... 🦤

**Comment by esune** [comment]
All the affected records have been updated.
