### ISSUE TITLE
Reprocess record in OrgBook BC

### ISSUE THREAD

**Issue by swcurran** [bcgov/von-bc-registries-agent#336]
From David Roberts, BC Registries:

I have just datafixed the following.  Please update Orgbook:
 
Corp_num: 1419778
Event: 18555626
New name: WEST RIG WELDING LTD.
 
David Roberts
Senior Database Administrator – BC Registries and Online Services

@droberts27 -- Hopefully this is David Roberts, BC Registries.

**Comment by amanji** [comment]
Closing as completed (see screenshot)
<img width="2558" alt="Screenshot 2023-11-07 at 9 48 25 AM" src="https://github.com/bcgov/von-bc-registries-agent/assets/5605464/6f38f61b-aecc-4076-9574-a170acf9b67c">
