### ISSUE TITLE
Reprocess record in OrgBook BC

### ISSUE THREAD

**Issue by droberts27** [bcgov/von-bc-registries-agent#337]
I have just datafixed the following. Please update OrgBook:

Corp_num: BC1349238
Event: 17337235
Old name: 1349238 B.C. LTD.
New name: TOUBA SOURCES INCORPORATED

OrgBook is missing the old name.

**Comment by amanji** [comment]
Should this be: 1349238 B.C. LTD or TOUBA SOURCES INCORPORATED?

**Comment by amanji** [comment]
Current state in OrgBook:

<img width="2558" alt="Screenshot 2023-11-07 at 9 55 50 AM" src="https://github.com/bcgov/von-bc-registries-agent/assets/5605464/51b7c76a-59d9-4235-8b32-c0bb391d9ef9">

**Comment by WadeBarnes** [comment]
I think @droberts27 is referring to the history missing the old name:

![image](https://github.com/bcgov/von-bc-registries-agent/assets/10504350/29920b8a-2954-48b5-b468-e9e4eddff012)

**Comment by droberts27** [comment]
Thanks @WadeBarnes .  That's correct.

**Comment by amanji** [comment]
Closing as completed. Please see screenshot:

<img width="2558" alt="Screenshot 2023-11-09 at 12 58 32 PM" src="https://github.com/bcgov/von-bc-registries-agent/assets/5605464/589f3f50-61a9-4e8b-8730-958a59a6e7dc">
