### ISSUE TITLE
difference in corp type between orgbook and COLIN

### ISSUE THREAD

**Issue by schaturv18** [bcgov/von-bc-registries-agent#338]
Hi,

Below companies are benefit companies but they are still showing as BC companies in Orgbook. 
Please make them benefit companies.

1147872
1227075
1088131
0863028
1033801

**Comment by schaturv18** [comment]
one more company here.
1371901

**Comment by swcurran** [comment]
@ianco or @amanji — can you arrange to have these companies reprocessed?

@schaturv18 — were these changed in the backend, or were there events that triggered the change?  If there were events, they should have been picked up by OrgBook.  Anything special/weird/different happen in updating the entities?

**Comment by WadeBarnes** [comment]
It appears these updates were made on the COLIN side without events.  @schaturv18, please correct me if I'm wrong.

These types of discrepancies get picked up by our nightly audit scripts.  I synced everything up this morning when reviewing the audit alerts.

**Comment by schaturv18** [comment]
Hi problem with these is that the event time for these companies is in the past and thats why they do not get picked up by orgbook. They come from modernised world and this is the reason for event time mismatch.

We have 3 more companies that are benefit companies at COLIN side by BC company on orgbook side. Can this be updated as well. Its because of a code issue on modernized world and we are working on fixing it.

BC1101632
BC1212477
BC0659462

**Comment by WadeBarnes** [comment]
> BC1101632 BC1212477 BC0659462

All three are showing as benefit companies on the OrgBook side.  They may have been included in the updates this morning.
