### ISSUE TITLE
Sole proprietorships not showing up in Orgbook

### ISSUE THREAD

**Issue by droberts27** [bcgov/von-bc-registries-agent#339]
Hello Orgbook Team - Why are the following not showing up in Orgbook?  They were registered before Sole Proprietorships were modernized in October, 2022.

'FM0578619',
'FM0677081',
'FM0791985',
'FM0840190',
'FM0814438',
'FM0438501',
'FM0485277',
'FM0486439',
'FM0412628',
'FM0490783',
'FM0497782',
'FM0508878',
'FM0531655',
'FM0610227',
'FM0651117',
'FM0651155',
'FM0651177',
'FM0652737',
'FM0651174',
'FM0651120',
'FM0651122',
'FM0603056',
'FM0852951',
'FM0808735',
'FM1011132',
'FM0440317'
'FM1037710'

**Comment by swcurran** [comment]
@amanji — could you please reschedule these for processing and see if they show up?  Let’s try that first.

@WadeBarnes — have these shown up in recent audit runs?

@droberts27 — how did you determine that these were missing?  What triggered that?  I’d like us to determine the underlying issue.

**Comment by droberts27** [comment]
This came up on our daily email "BC Reg Audit: BC Registries Audit (prod)" from no-reply@bcregaudit.gov.bc.ca

**Comment by ianco** [comment]
FYI just sent an email with some background information on how this came up.

**Comment by WadeBarnes** [comment]
Assigned to myself for visibility.

**Comment by WadeBarnes** [comment]
All of these corps have been queued and processed.  They are all appearing in the OrgBook now.
