### ISSUE TITLE
Below company needs to be a benefit company in orgbook

### ISSUE THREAD

**Issue by schaturv18** [bcgov/von-bc-registries-agent#340]
BC1390906 needs to changed to benefit company to be sync with COLIN.

**Comment by WadeBarnes** [comment]
Best to process following a clean run of the audit script in the morning, when activity is lower.  Typically there are too many changes in flux during the day to manually fix issues like this.  I just ran the audit script and there are a number of discrepancies being reported, which will likely be resolved in the next little while.

**Comment by WadeBarnes** [comment]
@schaturv18, Do you know if it would be possible to associate these types of changes to events?  If they were, they would get picked up automatically rather than having to be processed manually.

**Comment by schaturv18** [comment]
Yes, there is an event associated. but in this case this event came from a different source and the event time was in the past so I do not think it will be picked by orgbook.

**Comment by WadeBarnes** [comment]
Interestingly this corp is not appearing in the daily audit log as being out of sync with COLIN.  It is listed in the OrgBook as a `BC Company` and not a `Benefit Company` as indicated.

Two other corps appeared in the logs this morning for the the `BEN/BC` discrepancy, but not this one.

@schaturv18, Could you please confirm.  I'll have a look at the COLIN data from our perspective as well.

**Comment by schaturv18** [comment]
Hi Wade,

Sorry for the confusion. This issue can be closed now. No further action is required. Its suppose to be a BC company.
