### ISSUE TITLE
Sole proprietorships reported as missing in OrgBook

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-bc-registries-agent#341]
The sole proprietorships [`FM0412628`](https://orgbook.gov.bc.ca/entity/FM0412628) and [`FM0497782`](https://orgbook.gov.bc.ca/entity/FM0497782) are being reported as missing from the OrgBook by the BC Reg Audit Script's COLIN audit.  The latest LEAR audit shows no records are missing.

This has occurred since a number of LEAR records were updated to address https://github.com/bcgov/von-bc-registries-agent/issues/339.

The fact that these records are being reported by the COLIN audit seems to indicate the records are still in COLIN, but for some reason the audit script can't find them or is not including them in the scope of the COLIN audit.

**Comment by WadeBarnes** [comment]
cc @droberts27, @esune

**Comment by WadeBarnes** [comment]
@droberts27, Any insight into the state of these records on the COLIN and LEAR side of things?

**Comment by swcurran** [comment]
@droberts27 — is there a place that we can put these issues in the BC Registries backlog?  These types of things are not OrgBook BC issues — they just surface because OrgBook BC is pulling inconsistent data from COLIN and LEAR.

**Comment by WadeBarnes** [comment]
Update from David

This issue spans LEAR, CPRD, and Orgbook.

FM0412628 and FM0497782 were created as sole proprietorships (SP) in CPRD and included in OrgBook as SP.  During October, 2022 they were migrated to LEAR as SP and frozen in CPRD.  There have been no subsequent filings in LEAR.  During August, 2023 they were datafixed in CPRD to be Limited Partnerships (LP).  Currently they are frozen in CPRD and incorrectly showing as SP in LEAR and Orgbook.

The solution is:

David:  unfreeze FM0412628 and FM0497782 in CPRD
Richard:  Delete FM0412628 and FM0497782 from LEAR
Orgbook:  Update FM0412628 and FM0497782 to be LP in Orgbook

**Comment by swcurran** [comment]
To be a little more precise — `Orgbook: Requeue FM0412628 and FM0497782` to be clear that we don’t do anything in OrgBook other than take what is retrieved from BC Registries systems.

Thanks for the investigation and updates @WadeBarnes !

**Comment by WadeBarnes** [comment]
David has unfrozen the affected records.  Next step is with Richard.

**Comment by WadeBarnes** [comment]
Richard deleted the records from LEAR.

I requeued and reprocessed the records and now they are showing up in OrgBook as LPs as expected.

https://orgbook.gov.bc.ca/search?q=FM0412628&category%3Aentity_type=&credential_type_id=&inactive=&page=1
![image](https://github.com/bcgov/von-bc-registries-agent/assets/10504350/c0da0640-c201-4d90-a5ed-4912c99d4ed2)

https://orgbook.gov.bc.ca/search?q=FM0497782&category%3Aentity_type=&credential_type_id=&inactive=&page=1
![image](https://github.com/bcgov/von-bc-registries-agent/assets/10504350/a7262c6b-0e3d-45a1-913f-1ba89d1627b6)
