### ISSUE TITLE
Please update the name for A0131488

### ISSUE THREAD

**Issue by schaturv18** [bcgov/von-bc-registries-agent#343]
As an urgent datafix we have to update the name of A0131488 to "100+ ACCOUNTING INC.".
Please update orgbook to reflect the same. Thanks.

**Comment by esune** [comment]
> As an urgent datafix we have to update the name of A0131488 to "100+ ACCOUNTING INC.". Please update orgbook to reflect the same. Thanks.

@schaturv18 has the name been updated in the source system (LEAR or COLIN)? If so, we can re-queue the organization for processing on the OrgBook side.

c.c.: @WadeBarnes

**Comment by schaturv18** [comment]
Yes, its been updated in Colin.

**Comment by WadeBarnes** [comment]
Done; https://orgbook.gov.bc.ca/entity/A0131488
