### ISSUE TITLE
Determine URL and email address to use for BC Registries Agent issuer registration

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-bc-registries-agent#38]
This is what the current registration look like;
![image.png](https://images.zenhubusercontent.com/5adfb6864b5806bc2bd08363/df280a16-8dc3-4bea-a4f8-2b829be0d93f)

The URL is the route back to the BC Registries Agent, and there are no web pages implemented there, and the proxy providing access into the environment is slated for removal.

**Comment by ianco** [comment]
Updated locally, will be in next commit/PR.

**Comment by jljordan42** [comment]
Looks appropriate
