### ISSUE TITLE
Suppress issuance of Address Credential

### ISSUE THREAD

**Issue by jljordan42** [bcgov/von-bc-registries-agent#56]
For the initial release of BC TheOrgBook we will not be issuing address credentials.

**Comment by swcurran** [comment]
Issuing or showing?  Should we not issue them and not show them?

**Comment by jljordan42** [comment]
Not Issue and Not show ... for now

**Comment by swcurran** [comment]
@ianco - I assume you can do this pretty easily.  We'll need a plan (which I assume is also easy) for how to add the addresses when we are ready to issue them.

**Comment by ianco** [comment]
I will generate the address credentials and store in the event processor database under a special status of "Not Issued".

These will not be issued to TOB but can be issued in the future (by changing the status to "un-processed").
