### ISSUE TITLE
Potential error in the "Name Effective Date"

### ISSUE THREAD

**Issue by swcurran** [bcgov/von-bc-registries-agent#69]
Found this example organization: https://theorgbook.pathfinder.gov.bc.ca/en/topic/registration/BC0430308/cred/559582

It was a company registered in 1992 and appears to have been shutdown in 2004.

According to TheOrgBook page linked above, the "Name Effective Date" is 2004, which is unlikely.  Chances are the name was effective starting in 1992, or perhaps later if there was a name change.  But it should not be a name change at the same time the company was dissolved.

This could make setting the Name Effective date more difficult - search back through all events to find a name change, if none, use Registration Effective Date.

Please investigate - or have

**Comment by ianco** [comment]
For this company in the bc registries database (prod):

- There is one record in the corp_name table, with start_event_id 3872841 (end_event_id is null)
- The name effective date is derived from the event date
- The event date for this event is 2004-03-26 (possibly this date was set by a data conversion process) - the event type is CONVICORP
- There is no filing for this event

**Comment by swcurran** [comment]
My $0.02CDN - in a situation like this, where there is no complete history, and hence, no known "Name Effective Date", I would set the value to the "Registration Effective Date" rather than the date of the last known event.  Since relatively few entities likely have a name change event (I would bet less than 1%, but who knows), this is most likely to be correct.

That said - definitely a business rule.  Is there a potential negative impact if the date is incorrect but too early (reg date) vs. incorrect and too late (status event)?  Perhaps the right thing to do is put "N/A" (not available).

Anyway - something for the BC Reg team to consider.

**Comment by ianco** [comment]
@swcurran agree but we don't have any heuristics around what a complete history looks like or not.

I'll send the question to the BC Reg folks and see what they have to say.  (In the meantime I'll keep this ticket open.)
