### ISSUE TITLE
Add an "Issuance Reason Code" in the Registration Credential

### ISSUE THREAD

**Issue by swcurran** [bcgov/von-bc-registries-agent#72]
Work with BC Registry to come up with an issuance reason code per event type that can be included in the Registration Credential.  From TheOrgBook perspective, we'd like to present a timeline of the Credential and the Organization, and on that timeline, show this field (converted into English/French as appropriate) for why a Credential was issued (e.g. New Registration, Annual Renewal, Dissolved, etc.).

This is seen as a show stopper for launch of the post-SLN, so please prioritize this accordingly.

Presumably that means we need to know:

* The list of event types
* A name for each event type
* A way to detect the type of each event
* Translations for each event type

Having said that - if differences between event types are too subtle for the public, I would say it's perfectly reasonable to have one Credential Issuance Reason Code for multiple event types.  Use good judgement.

**Comment by ianco** [comment]
Per meeting with BC Registries, use the Filing Description (if available) or Event Description (if filing is NOT available) as the credential reason description.

Note that event and filing descriptions available in BC Reg are english only, translations will need to be obtained (will be in a separate ticket).
