### ISSUE TITLE
Credential posting failures during high volumes

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-bc-registries-agent#94]
We continue to see credential posting failures occasionally during sustained high volume processing such as initial data loads.

The issue occurs due to connection/response timeouts between the `agent` and the `tob-api` and is directly related to the `tob-api`'s ability to effectively handle the volume of requests from the `agent` at any given time.

When the `tob-api` is unable to effectively handle the load it cannot process the requests fast enough, causing some of the `agent` requests to time out, which results in the following error message being logged for the `process` failure:
```
Bad response from post_json: (504) <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

Under normal initial load conditions we pre-configure the following resources  (for BC Registries);
- 2 mara containers;
  - One dedicated to processing the corporate records.
  - One dedicated to posting credentials.
- 8 agent containers to service the credential post requests.
- 5 tob-api pods to process the posted credentials.

The mara and agent containers are scaled manually, the tob-api containers are configured to auto-scale, however for initial data loads we ensure the tob-api containers are pre-scaled to 5 instances.  Under these conditions there are enough tob-api containers to easily handle the requests from the 8 agent containers.

The failures start to occur when there are fewer tob-api containers servicing the high volume of requests.  The problem is most notable when there is only a single tob-api container servicing all of the requests.  The one container simply cannot keep up, and many agent requests timeout before the tob-api can respond and/or the number of containers is scaled up enough to be able to handle the sustained volume.

This condition can occur for a number of different reasons, including:
- The pod containing the tob-api pod gets moved to different compute node; due to evacuation, scheduling, or load balancing.
- The number of tob-api containers is scaled down; due to decreased resource utilization which can be caused by lulls in the volume of credentials being processed.

**Comment by WadeBarnes** [comment]
Testing indicates a minimum of 3 tob-api containers are required in order to process credentials under sustained high volume loads, using the conditions described above, without error, for long enough to allow the tob-api containers to fully scale out to their maximum number.  Running with 2 tob-api containers dramatically reduces the number of errors, but does not eliminate them.

**Comment by WadeBarnes** [comment]
Having a minimum of 3 tob-api containers at the ready all the time is general not desirable, since they will be sitting there completely idle for the majority of their life under normal conditions.

We should consider extending the timeout on the agent side so the agent containers are more patient when there are fewer tob-api containers to service the requests.  This would allow the tob-api containers more time to finish processing the credentials and more time for additional tob-api containers to be spun up to handle the load.

**Comment by WadeBarnes** [comment]
@ianco, Could you confirm the current request and connection timeout settings, and look into making them configurable so we have the ability to tune them for a given environment?

**Comment by ianco** [comment]
@WadeBarnes  can we chat about this one?  Maybe tomorrow (Wed) when we're both in the office (I'm at UBC today)

**Comment by ianco** [comment]
I will update the postgres wallet to make the various parameters configurable via wallet config attributes.
